python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta0.0_f0.0_Hswim_0.05  --beta 0.0 --task_coef02 0.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta0.0_f1.0_Hswim_0.05  --beta 0.0 --task_coef02 1.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta0.0_f2.0_Hswim_0.05  --beta 0.0 --task_coef02 2.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta0.0_f3.0_Hswim_0.05  --beta 0.0 --task_coef02 3.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta10.0_f0.0_Hswim_0.05  --beta 10.0 --task_coef02 0.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta10.0_f1.0_Hswim_0.05  --beta 10.0 --task_coef02 1.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta10.0_f2.0_Hswim_0.05  --beta 10.0 --task_coef02 2.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta10.0_f3.0_Hswim_0.05  --beta 10.0 --task_coef02 3.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta0.0_A0.0_Hswim_0.05  --beta 0.0 --task_coef01 0.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta0.0_A0.5_Hswim_0.05  --beta 0.0 --task_coef01 0.5
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta0.0_A0.8_Hswim_0.05  --beta 0.0 --task_coef01 0.8
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta0.0_A0.3_Hswim_0.05  --beta 0.0 --task_coef01 0.3
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta10.0_A0.0_Hswim_0.05  --beta 10.0 --task_coef01 0.0
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta10.0_A0.5_Hswim_0.05  --beta 10.0 --task_coef01 0.5
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta10.0_A0.8_Hswim_0.05  --beta 10.0 --task_coef01 0.8
python runner.py main/SAC_aux_gym.py --config configs/SAC_swim_exp.yaml --exp-dir results/SAC_phi_gauss_beta10.0_A0.3_Hswim_0.05  --beta 10.0 --task_coef01 0.3
