exp_name: swim
lr: 0.0003 
entropy_coef: 0.01
value_loss_coef: 0.5
gamma: 0.99
use_gae: True
gae_lambda: 0.95
eps: 0.00001
num_steps: 2048 
num_env_steps: 10000000
max_grad_norm: 0.5
num_processes: 1 
use_linear_lr_decay: True
use_proper_time_limits: True
clip-param: 0.2
log_interval: 1 
ppo_epoch: 10 
num_mini_batch: 32 
seeds: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]