exp_name: ccb
memory: NER
discrete: 50
gamma: 0.9
epoch_number: 1000
rollout_step: 20
train_step: 40
batch_size: 64
weight_decay: 0.0001
psd_batch: 2000
critic_lr: 0.01
actor_lr: 0.001
type: 0
noise: 0
rand_max: 0
buffer_size: 20000
seeds: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]