exp_name: swim
memory: NER
policy: Gaussian
gamma: 0.99
beta: 0.1
tau: 0.005
lr: 0.0003
alpha: 0.2
automatic_entropy_tuning: True
epoch_number: 1000
rollout_step: 100
train_step: 40
aux_coef: 0.1
batch_size: 64
weight_decay: 0.0001
psd_batch: 2000
updates_per_step: 20
start_steps: 10000
target_update_interval: 1
rand_max: 0
buffer_size: 1000000
seeds: [7,8,9,10]

task_coef00: 0.2
task_coef01: 0.5
task_coef02: 1.0 
task_coef03: 0.1 
task_coef04: 9.5
task_coef05: 0.5
task_coef06: 1.0