exp_name: swim
memory: NER
policy: Gaussian
gamma: 0.99
beta: 0.0
tau: 0.005
lr: 0.0003
alpha: 0.2
automatic_entropy_tuning: True
epoch_number: 20000
rollout_step: 1
batch_size: 256
hidden: 256
weight_decay: 0.0001
updates_per_step: 1
target_update_interval: 1
buffer_size: 20000
seeds: [0,1,2,3,4,5,6,7,8,9]

task_coef00: 0.2
task_coef01: 0.5
task_coef02: 1.0 
task_coef03: 0.1 
task_coef04: 9.5
task_coef05: -0.5
task_coef06: 1.0