exp_name: swim
memory: NER
K_head: 1
alpha: 0.1
task_coef01: 0.2
scan_number: 50
beta: 0.1
gamma: 0.99
lambda_g: 1.0
epoch_number: 1000
rollout_step: 100
train_step: 100
batch_size: 64
weight_decay: 0.01
psd_batch: 10000
critic_lr: 0.01
actor_lr: 0.001
tao: 0.90
tao_rollout: 0.98
type: 0
noise: 0
rand_max: 100
buffer_size: 100000
seeds: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]